### ISSUE TITLE
Problems running SZZ++ implementation

### ISSUE THREAD

**Issue by arturfarias** [saheel1115/szz#1]
I'm trying to run SZZ ++, but it has several exceptions and the only tests that work correctly and the number 1 "Clone the project provided" I installed the following dependencies: 

gitpython
psycopg2
R language

But the errors continue. I used the commands: 

python main.py data/ libgit2 https://github.com/libgit2/libgit2.git c 3 16 --steps 1 2 3 4 5
python main.py data/ bitcoin https://github.com/bitcoin/bitcoin.git cpp 3 16 --steps 5 6 7 8

Both have exceptions as outputs. I think it's some dependency I have not installed or some misconfiguration anyway, I'm using Ubuntu Mate 16.04 to test.

Follows the outputs shown.

```
---------------------------------------------------- 1. Clone the latest version of given project ----------------------------------------------------

Cloning into '/home/artur/Downloads/szz-master/data/projects/libgit2'...
remote: Counting objects: 77614, done.
remote: Compressing objects: 100% (22056/22056), done.
remote: Total 77614 (delta 54159), reused 77610 (delta 54155), pack-reused 0
Receiving objects: 100% (77614/77614), 36.25 MiB | 2.19 MiB/s, done.
Resolving deltas: 100% (54159/54159), done.
Checking connectivity... done.
---------------------------------------------------- 2. Dump the snapshots ----------------------------------------------------
Going to take snapshot for project /home/artur/Downloads/szz-master/data/projects/libgit2
Creating output directory at /home/artur/Downloads/szz-master/data/snapshots/
SELECT tag, project, min(commit_date), max(commit_date) FROM err_corr_july_2015.all_changes_tmp Where tag like 'c' and project = 'libgit2' group by tag, project

[]
Traceback (most recent call last):
  File "src/generate_snapshot_data/dump.py", line 176, in <module>
    commit_dates = fetchCommitDates(cfg, args.proj_dir, args.lang)
  File "src/generate_snapshot_data/dump.py", line 120, in fetchCommitDates
    assert(len(proj.projects) == 1)
AssertionError
---------------------------------------------------- 3. Dump the history of all commit changes ----------------------------------------------------
!! Please provide a valid directory, given: /home/artur/Downloads/szz-master/data/snapshots/libgit2
---------------------------------------------------- 4. Get list of bug-fixing commits from PostgreSQL ----------------------------------------------------
Error in fetching bugfix SHAs! Please check whether data exists in `err_corr_july_2015.all_changes_tmp` for `libgit2`
FATAL:  Peer authentication failed for user "saheel"

Traceback (most recent call last):
  File "src/szz/get_list_of_bugfix_SHAs.py", line 48, in <module>
    extractBugfixSHAs(sys.argv[1], sys.argv[2])
  File "src/szz/get_list_of_bugfix_SHAs.py", line 26, in extractBugfixSHAs
    con = psycopg2.connect(database='baishakhi', user='saheel')
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  Peer authentication failed for user "saheel"

---------------------------------------------------- 5. Run SZZ to get bug data ----------------------------------------------------

    Usage: python szz.py <path_to_project_corpus_dir>
                         <path_to_project_snapshots_dir> 
                         <path_to_bugfix_SHAs_file> 
                         <num_of_cores> 
                         [<path_to_bug_report_times_file>]

    Sample usage: python szz.py data/corpus/libgit2/ data/snapshots/libgit2/ data/bf_shas/libgit2.bf 8

    Run 'pydoc /path/to/szz.py' to see detailed documentation on the `szz` module, especially the `szz.szz()` function.
    Traceback (most recent call last):
  File "src/szz/szz.py", line 189, in <module>
    szz(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
  File "src/szz/szz.py", line 110, in szz
    `bugfix_SHAs_filename` should be a valid file.""")
IOError: 
Given paths are not as expected.

                             `project_snapshots_path` and `project_corpus_path` should be valid directories.

                             `bugfix_SHAs_filename` should be a valid file.
---------------------------------------------------- main.py DONE for libgit2 ----------------------------------------------------
```
```
---------------------------------------------------- 5. Run SZZ to get bug data ----------------------------------------------------

    Usage: python szz.py <path_to_project_corpus_dir>
                         <path_to_project_snapshots_dir> 
                         <path_to_bugfix_SHAs_file> 
                         <num_of_cores> 
                         [<path_to_bug_report_times_file>]

    Sample usage: python szz.py data/corpus/libgit2/ data/snapshots/libgit2/ data/bf_shas/libgit2.bf 8

    Run 'pydoc /path/to/szz.py' to see detailed documentation on the `szz` module, especially the `szz.szz()` function.
    Traceback (most recent call last):
  File "src/szz/szz.py", line 189, in <module>
    szz(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
  File "src/szz/szz.py", line 110, in szz
    `bugfix_SHAs_filename` should be a valid file.""")
IOError: 
Given paths are not as expected.

                             `project_snapshots_path` and `project_corpus_path` should be valid directories.

                             `bugfix_SHAs_filename` should be a valid file.
---------------------------------------------------- 6. Dump the CSV files with bug data into PostgreSQL tables ----------------------------------------------------
Traceback (most recent call last):
  File "src/szz/dump_bugdata_into_psql_table.py", line 57, in <module>
    with open(bugdata_path, 'rb') as bugdata_file:
IOError: [Errno 2] No such file or directory: '/home/artur/Downloads/szz-master/data/corpus/bitcoin//ss_bugdata.csv'
---------------------------------------------------- 7. Generate AST-type data ----------------------------------------------------
Traceback (most recent call last):
  File "src/generate_asts_and_type_data/generate_typedata.py", line 4, in <module>
    from parse_srcML import parseSrcmlForTypedata
  File "/home/artur/Downloads/szz-master/src/generate_asts_and_type_data/parse_srcML.py", line 10, in <module>
    from lxml import etree
ImportError: No module named lxml
---------------------------------------------------- 8. Gather generated AST-type data into CSV files ----------------------------------------------------
Corpus path or Snapshot path inferred from given data directory and project name is invalid. Please check the input.
The paths that I have are:
Corpus path: /home/artur/Downloads/szz-master/data/corpus/bitcoin
Snapshot path: /home/artur/Downloads/szz-master/data/snapshots/bitcoin
Traceback (most recent call last):
  File "src/generate_asts_and_type_data/gather_typedata_into_csv.py", line 62, in <module>
    raise ValueError
ValueError
---------------------------------------------------- main.py DONE for bitcoin ----------------------------------------------------
```

**Comment by ManelGrichi** [comment]
I had the same problem. So, i investigated their database and i found that the problem is related to the table used, there is no information related to libgit2 in Table 'err_corr_july_2015.all_changes_tmp'. 
I suggest to you to use table 'err_corr_c.everything' instead of 'err_corr_july_2015.all_changes_tmp'. 
You can change it in config.ini
Hope that it can help.

**Comment by saheel1115** [comment]
Check out the other issue with my comment on it for a better idea on how to resolve these exceptions starting Step 2: https://github.com/saheel1115/szz/issues/3#issuecomment-455847746
