### ISSUE TITLE
Problems with the database and table err_corr_july_2015.all_changes_tmp

### ISSUE THREAD

**Issue by ManelGrichi** [saheel1115/szz#3]
Hello, i'm trying to create the snapshots of a given project but i did not succeed, i think that the problem is related to the database connexion.  Are the information in config.ini up-to-date?
Only the clone option is working among the steps offered by SZZ++

>  python main.py x libgit2 https://github.com/libgit2/libgit2.git c 3 16 --steps 2
Going to take snapshot for project C:/home/szz/manel/projects/libgit2
Creating output directory at C:/home/szz/manel/snapshots/
SELECT tag, project, min(commit_date), max(commit_date) FROM err_corr_july_2015.all_changes_tmp Where tag like 'c' and project = 'C:                                        /home/szz/manel/projects/libgit2' group by tag, project

> []
Traceback (most recent call last):
  File "src/generate_snapshot_data/dump.py", line 176, in <module>
    commit_dates = fetchCommitDates(cfg, args.proj_dir, args.lang)
  File "src/generate_snapshot_data/dump.py", line 120, in fetchCommitDates
    assert(len(proj.projects) == 1)
AssertionError

Any help please? Is there any special configuration that we should do before running step 2?
Thank you

**Comment by ManelGrichi** [comment]
Actually, i succeeded to connect to the database, in table err_corr_july_2015.all_changes_tmp i can not see any project named libgit2 (trying to follow the example in Main.py)
How is this table updated please?

**Comment by saheel1115** [comment]
Hey, execute the script `/src/parse_git_log/classify.sh` to populate the all_changes table.

I was following the scripts called by `classify.sh` and found that there are a lot of hard-coded values in there (like file extension `.java`, paths to the projects directory, name of project, paths to log files, etc.). So it'll require some trial and error with the correct modifications to the called scripts before you can successfully populate the table. Take a look at `DbChange.dump_change()` to know the schema of the table.

Also, remember to change the database config `.ini` file according to your system.

Good luck!

PS: I have not written this part of the code so I too am a bit unfamiliar with it. Just read the code, follow the control flow, and you should be able to grasp what's happening. That's what I did just now to answer your question :) Also, if you end up making (readability/portability/functionality) improvements to the codebase, please create a pull request!
